services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
    ports:
      - "${PGPORT}:5432"
