services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: firehose_development
      # This is only for local development, so this is fine!
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
