# TODO: Because of url.URL.Parse, this MUST end in a slash. Fix that.
url-base = "http://localhost:8002/v1/"
user-id = "84b9cc2d-839d-4a49-abf5-eea976cea879"
api-key = "q0qdbnemw0xdr9t1bpme8x8ezfnf2dtv1g58e466fdmvhsk1wnj0"
