// Code generated by sqlc. DO NOT EDIT.
// source: drop_tags.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

const dropTagApply = `-- name: DropTagApply :one
insert into drop_tags
(drop_id, tag_id)
values ($1, $2)
returning id, drop_id, tag_id, created_at
`

type DropTagApplyParams struct {
	DropID uuid.UUID
	TagID  uuid.UUID
}

func (q *Queries) DropTagApply(ctx context.Context, arg DropTagApplyParams) (DropTag, error) {
	row := q.db.QueryRowContext(ctx, dropTagApply, arg.DropID, arg.TagID)
	var i DropTag
	err := row.Scan(
		&i.ID,
		&i.DropID,
		&i.TagID,
		&i.CreatedAt,
	)
	return i, err
}
