// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
	"github.com/metagram-net/firehose/db/types"
)

type ApiKey struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	HashedSecret []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Drop struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     sql.NullString
	URL       string
	Status    types.DropStatus
	MovedAt   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DropTag struct {
	ID        uuid.UUID
	DropID    uuid.UUID
	TagID     uuid.UUID
	CreatedAt time.Time
}

type SchemaMigration struct {
	ID    int32
	Slug  string
	RunAt time.Time
}

type Tag struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	EmailAddress string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
